image:
  repository: ${IMAGE}
  tag: ${RELEASE}
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: ory-oel-gcr-secret
service:
  public:
    enabled: true
    type: LoadBalancer
    port: ${PUBLIC_PORT}
    name: http
  admin:
    enabled: true
    type: LoadBalancer
    port: ${ADMIN_PORT}
    name: http
maester:
  enabled: false
hydra:
  dev: true
  automigration:
    enabled: true
  config:
    serve:
      public:
        port: ${PUBLIC_PORT}
      admin:
        port: ${ADMIN_PORT}
    dsn: "cockroach://root@${CRDB_FQDN}:26257/hydra?sslmode=disable"